version: '3.8'

services:

  db:
    image: postgres
    restart: always
    container_name: k8s-example-db
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: user
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
  api:
    build:
      context: ../spring-api
    image: omidmohebbi/simple-spring-api:latest
    container_name: k8s-example-api
    ports:
      - "8080:8080"