apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-stack
  labels:
    app: app-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-stack
  template:
    metadata:
      labels:
        app: app-stack
    spec:
      containers:
        - name: app-stack-api-1
          image: omidmohebbi/simple-spring-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/mydatabase"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "mydatabase"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
#          volumeMounts:
#            - name: postgres-storage
#              mountPath: /var/lib/postgresql/data
#    volumes:
#      - name: postgres-storage
#        emptyDir: {}